services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            target: prod
            args:
                WWWUSER: ${WWWUSER}
                WWWGROUP: ${WWWGROUP}
        restart: always
        container_name: shafiqul-enterprise-app
        working_dir: /var/www
        volumes:
            - .:/var/www:cached
            - .docker/php/supervisord.conf:/etc/supervisord.conf
            - .docker/php/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
        depends_on:
            - mysql
            - redis
        networks:
            - shafiqul-enterprise-network

    nginx:
        image: nginx:alpine
        container_name: shafiqul-enterprise-nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - shafiqul-enterprise-network

    mysql:
        image: mysql:8.3
        container_name: shafiqul-enterprise-mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - shafiqul-enterprise-network

    redis:
        image: redis:alpine
        container_name: shafiqul-enterprise-redis
        restart: always
        volumes:
            - redis_data:/data
        networks:
            - shafiqul-enterprise-network

    mailpit:
        image: axllent/mailpit
        container_name: shafiqul-enterprise-mailpit
        restart: always
        ports:
            - "8025:8025" # Web UI
            - "1025:1025" # SMTP
        networks:
            - shafiqul-enterprise-network

volumes:
    mysql_data:
    redis_data:

networks:
    shafiqul-enterprise-network:
        driver: bridge
